### Create Product
POST http://localhost:8080/product/create
Content-Type: application/json

{
  "name": "keraksiz",
  "price": 110040,
  "typeId": 1,
  "statusId": 1
}

### Get All
GET http://localhost:8080/product/getAll
Content-Type: application/json

### Get by id
GET http://localhost:8080/product/
Content-Type: application/json

### Update by id
PUT http://localhost:8080/product/update/11
Content-Type: application/json

{
  "name": "Olsdcscsdma",
  "price": 12000.0,
  "typeId": 3,
  "statusId": 2
}

### Delete by id
DELETE http://localhost:8080/product/11