### CREATE
POST http://localhost:8080/type/create
Content-Type: application/json

{
  "name": "Kiyim"
}

### Get by id
GET http://localhost:8080/type/1

### Get All
GET http://localhost:8080/type/getAll

### Update by Id
PUT http://localhost:8080/type/1
Content-Type: application/json

{
  "name": "Elektronika jihozlari"
}

### Delete by id
DELETE http://localhost:8080/type/1
